# -*- coding: utf-8 -*-
"""Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yvMBv6oCBAZ_iKFmyEt1JT6okaZX-Bkp
"""

import math

def Calculator(Operator, X, Y):
    if Operator == "Add":
        Result = X + Y
    elif Operator == "Subtract":
        Result = X - Y
    elif Operator == "Multiply":
        Result = X * Y
    elif Operator == "Divide":
        if Y == 0:
            Result = "Invalid value for denominator, can't divide by 0!"
        else:
            Result = X / Y
    elif Operator == "Square":
        Result = X**2, Y**2
    elif Operator == "Power":
        Result = X ** Y
    elif Operator == "SquareRoot":
        Result = math.sqrt(X), math.sqrt(Y)
    else:
        Result = "Invalid operator"
    return Result